name: Run Market Data Analysis

on:
  schedule:
    # Runs at 4:05, 8:05, 12:05, 16:05, 20:05, and 00:05 every day
    - cron: '5 */4 * * *'
  workflow_dispatch:

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace '3.x' with your desired Python version

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Analysis Script
      env:
        BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python main.py
